# coding: utf-8

"""
    Jobbergate-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.3.0a1
    Contact: info@omnivector.solutions
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field, StrictInt, StrictStr

class ActiveJobSubmission(BaseModel):
    """
    Specialized model for the cluster-agent to pull an active job_submission.  # noqa: E501
    """
    id: StrictInt = Field(...)
    name: StrictStr = Field(...)
    slurm_job_id: StrictInt = Field(...)
    __properties = ["id", "name", "slurm_job_id"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ActiveJobSubmission:
        """Create an instance of ActiveJobSubmission from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ActiveJobSubmission:
        """Create an instance of ActiveJobSubmission from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ActiveJobSubmission.parse_obj(obj)

        _obj = ActiveJobSubmission.parse_obj({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "slurm_job_id": obj.get("slurm_job_id")
        })
        return _obj


