# coding: utf-8

"""
    Jobbergate-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.3.0a1
    Contact: info@omnivector.solutions
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class FileType(str, Enum):
    """
    File type enum.
    """

    """
    allowed enum values
    """
    ENTRYPOINT = 'ENTRYPOINT'
    SUPPORT = 'SUPPORT'

    @classmethod
    def from_json(cls, json_str: str) -> FileType:
        """Create an instance of FileType from a JSON string"""
        return FileType(json.loads(json_str))


