# coding: utf-8

"""
    Jobbergate-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.3.0a1
    Contact: info@omnivector.solutions
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictStr
from openapi_client.models.job_submission_status import JobSubmissionStatus

class JobSubmissionUpdateRequest(BaseModel):
    """
    Request model for updating JobSubmission instances.  # noqa: E501
    """
    name: Optional[StrictStr] = Field(None, description="The unique name of the job submission")
    description: Optional[StrictStr] = Field(None, description="A text field providing a human-friendly description of the job_submission")
    execution_directory: Optional[StrictStr] = Field(None, description="The directory on the cluster where the job should be executed")
    status: Optional[JobSubmissionStatus] = Field(None, description="The status of the job submission. Must be one of CREATED, SUBMITTED, REJECTED, DONE, ABORTED")
    __properties = ["name", "description", "execution_directory", "status"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> JobSubmissionUpdateRequest:
        """Create an instance of JobSubmissionUpdateRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> JobSubmissionUpdateRequest:
        """Create an instance of JobSubmissionUpdateRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return JobSubmissionUpdateRequest.parse_obj(obj)

        _obj = JobSubmissionUpdateRequest.parse_obj({
            "name": obj.get("name"),
            "description": obj.get("description"),
            "execution_directory": obj.get("execution_directory"),
            "status": obj.get("status")
        })
        return _obj


