# coding: utf-8

"""
    Jobbergate-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.3.0a1
    Contact: info@omnivector.solutions
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictInt, conint

class JobSubmissionAgentSubmittedRequest(BaseModel):
    """
    Request model for marking JobSubmission instances as SUBMITTED.  # noqa: E501
    """
    id: StrictInt = Field(..., description="The unique database identifier for the instance")
    slurm_job_id: Optional[conint(strict=True, ge=0)] = Field(None, description="The id for the slurm job executing this job_submission")
    __properties = ["id", "slurm_job_id"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> JobSubmissionAgentSubmittedRequest:
        """Create an instance of JobSubmissionAgentSubmittedRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> JobSubmissionAgentSubmittedRequest:
        """Create an instance of JobSubmissionAgentSubmittedRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return JobSubmissionAgentSubmittedRequest.parse_obj(obj)

        _obj = JobSubmissionAgentSubmittedRequest.parse_obj({
            "id": obj.get("id"),
            "slurm_job_id": obj.get("slurm_job_id")
        })
        return _obj


