line-length = 120

[lint]
extend-select = ["B", "E", "F", "I"]
extend-ignore = [
    "E501", # Line too long
]

[lint.isort]
known-first-party = [
    "jobbergate-core",
    "jobbergate-cli",
    "jobbergate-agent",
    "jobbergate-api",
    "jobbergate-docs",
    "jobbergate-test",
    "fake-sbatch",
]

[lint.per-file-ignores]

[format]
quote-style = "double"
