FROM centos:7

# Adapted from https://github.com/giovtorres/slurm-docker-cluster
ARG GOSU_VERSION=1.11

RUN set -ex \
    && yum makecache fast \
    && yum -y update \
    && yum -y install epel-release \
    && yum -y install \
       wget \
       bzip2 \
       perl \
       gcc \
       gcc-c++\
       git \
       gnupg \
       make \
       munge \
       munge-devel \
       python-devel \
       python-pip \
       python34 \
       python34-devel \
       python34-pip \
       mariadb-server \
       mariadb-devel \
       psmisc \
       bash-completion \
       vim-enhanced \
       autoconf \
       automake \
    && yum clean all \
    && rm -rf /var/cache/yum

RUN ln -s /usr/bin/python3.4 /usr/bin/python3

RUN pip install Cython nose && pip3.4 install Cython nose

RUN set -ex \
    && wget -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-amd64" \
    && wget -O /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-amd64.asc" \
    && export GNUPGHOME="$(mktemp -d)" \
    && gpg --batch --keyserver hkps://keys.openpgp.org --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4 \
    && gpg --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu \
    && rm -rf "${GNUPGHOME}" /usr/local/bin/gosu.asc \
    && chmod +x /usr/local/bin/gosu \
    && gosu nobody true

# Cmake
RUN set -x \
    && curl https://cmake.org/files/v3.12/cmake-3.12.3.tar.gz --output cmake-3.12.3.tar.gz \
    && tar -xzvf cmake-3.12.3.tar.gz cmake-3.12.3 \
    && pushd cmake-3.12.3 \
    && ./bootstrap --prefix=/usr/local \
    && make -j$(nproc) \
    && make install

RUN yum install -y libtool jansson jansson-devel libyaml-devel


# LibJWT
RUN set -x \
    && git clone https://github.com/benmcollins/libjwt.git \
    && pushd libjwt \
    && git checkout v1.12.0 \
    && autoreconf -i \
    && ./configure --prefix=/usr \
    && make \
    && make install

# Http-Parser
RUN set -x \
    && git clone https://github.com/nodejs/http-parser.git \
    && pushd http-parser \
    && git checkout tags/v2.9.4 \
    && make PREFIX=/usr \
    && make install

# JSON-C
RUN set -x \
    && git clone https://github.com/json-c/json-c.git \
    && pushd json-c \
    && git checkout tags/json-c-0.14-20200419 \
    && mkdir build/ \
    && cd build/ \
    && cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release .. \
    && make \
    && make install

# Use forked slurm with SKIP_LOCKDOWN
RUN set -x \
    && git clone https://github.com/omnivector-solutions/slurm.git \
    && pushd slurm \
    && git checkout dusktreader/hacked-slurm-for-docker \
    && ./configure --enable-debug --prefix=/usr --sysconfdir=/etc/slurm \
        --with-mysql_config=/usr/bin  --libdir=/usr/lib64 \
        --enable-slurmrestd --with-libcurl \
        --with-http-parser=/usr/local \
        --with-yaml=/usr \
        --with-json=/usr \
        --with-jwt=/usr \
    && make install \
    && install -D -m644 etc/cgroup.conf.example /etc/slurm/cgroup.conf.example \
    && install -D -m644 etc/slurm.conf.example /etc/slurm/slurm.conf.example \
    && install -D -m644 etc/slurmdbd.conf.example /etc/slurm/slurmdbd.conf.example \
    && install -D -m644 contribs/slurm_completion_help/slurm_completion.sh /etc/profile.d/slurm_completion.sh \
    && popd \
    && rm -rf slurm \
    && groupadd -r --gid=995 slurm \
    && useradd -r -g slurm --uid=995 slurm \
    && mkdir /etc/sysconfig/slurm \
        /var/spool/slurmd \
        /var/run/slurmd \
        /var/run/slurmdbd \
        /var/lib/slurmd \
        /var/log/slurm \
        /data \
    && touch /var/lib/slurmd/node_state \
        /var/lib/slurmd/front_end_state \
        /var/lib/slurmd/job_state \
        /var/lib/slurmd/resv_state \
        /var/lib/slurmd/trigger_state \
        /var/lib/slurmd/assoc_mgr_state \
        /var/lib/slurmd/assoc_usage \
        /var/lib/slurmd/qos_usage \
        /var/lib/slurmd/fed_mgr_state \
    && chown -R slurm:slurm /var/*/slurm* \
    && /sbin/create-munge-key

# Install Singularity
RUN yum install -y https://github.com/sylabs/singularity/releases/download/v3.10.2/singularity-ce-3.10.2-1.el7.x86_64.rpm

# Install MPICH
RUN yum install -y mpich-3.2 mpich-3.2-devel
RUN echo "module load mpi/mpich-3.2-x86_64" >> /etc/bashrc

ARG JWT_SECRET=supersecret

COPY etc/slurmdbd.conf /etc/slurm/slurmdbd.conf
RUN chown slurm:slurm /etc/slurm/slurmdbd.conf
RUN chmod 600 /etc/slurm/slurmdbd.conf
COPY etc/slurm.conf /etc/slurm/slurm.conf
# JWKS doesn't seem to work. Makes slurmrestd throw a 500
# COPY jwks.json /etc/slurm/jwks.json
RUN echo -n "$JWT_SECRET" > /etc/slurm/jwt_hs256.key

COPY etc/slurm-env.sh /etc/profile.d/slurm-env.sh

# Add local-user
RUN useradd -ms /bin/bash local-user

COPY etc/slurm-entrypoint.sh /usr/local/bin/slurm-entrypoint.sh
ENTRYPOINT ["/usr/local/bin/slurm-entrypoint.sh"]

CMD ["slurmdbd"]
