FROM ubuntu:jammy-20211122


ARG GOSU_VERSION=1.11

RUN set -ex \
    && apt update \
    && apt install wget gpg -y \
    && wget -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-amd64" \
    && wget -O /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-amd64.asc" \
    && export GNUPGHOME="$(mktemp -d)" \
    && gpg --batch --keyserver hkps://keys.openpgp.org --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4 \
    && gpg --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu \
    && rm -rf "${GNUPGHOME}" /usr/local/bin/gosu.asc \
    && chmod +x /usr/local/bin/gosu \
    && gosu nobody true



COPY ubuntu-hpc.pub .

RUN set -ex \
    && export GNUPGHOME="$(mktemp -d)" \
    && cat ubuntu-hpc.pub | gpg --dearmor -o /usr/share/keyrings/ubuntu-hpc.gpg \
    && echo "deb [signed-by=/usr/share/keyrings/ubuntu-hpc.gpg] https://ppa.launchpadcontent.net/ubuntu-hpc/slurm-wlm-23.02/ubuntu/ jammy main" > /etc/apt/sources.list.d/ubuntu-hpc-slurm.list \
    && gpg --keyserver hkp://keyserver.ubuntu.com:80  --recv-keys AE87121DC3E4A0B0F81FF023F6D0C5D5C6BEB37B \
    && apt update \
    && apt install slurm-wlm-basic-plugins slurmrestd slurmd slurmdbd slurmctld mysql-client -y \
    && rm -rf "${GNUPGHOME}" ubuntu-hpc.pub


ARG JWT_SECRET=supersecret

COPY etc/slurmdbd.conf /etc/slurm/slurmdbd.conf
RUN chown slurm:slurm /etc/slurm/slurmdbd.conf
RUN chmod 600 /etc/slurm/slurmdbd.conf
COPY etc/slurm.conf /etc/slurm/slurm.conf
# JWKS doesn't seem to work. Makes slurmrestd throw a 500
# COPY jwks.json /etc/slurm/jwks.json
RUN echo -n "$JWT_SECRET" > /etc/slurm/jwt_hs256.key

COPY etc/slurm-env.sh /etc/profile.d/slurm-env.sh

# Add local-user
RUN useradd -ms /bin/bash local-user


RUN mkdir /var/spool/slurmctld \
    && mkdir /var/spool/slurmd \
    && chown -R slurm:slurm /var/spool/slurmctld \
    && chown -R slurm:slurm /var/spool/slurmd

COPY etc/slurm-entrypoint.sh /usr/local/bin/slurm-entrypoint.sh
ENTRYPOINT ["/usr/local/bin/slurm-entrypoint.sh"]

CMD ["slurmdbd"]
