# coding: utf-8

"""
    Jobbergate-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.3.0a1
    Contact: info@omnivector.solutions
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.job_submission_list_view import JobSubmissionListView  # noqa: E501

class TestJobSubmissionListView(unittest.TestCase):
    """JobSubmissionListView unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> JobSubmissionListView:
        """Test JobSubmissionListView
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `JobSubmissionListView`
        """
        model = JobSubmissionListView()  # noqa: E501
        if include_optional:
            return JobSubmissionListView(
                id = 101,
                name = 'test-job-submission-77',
                owner_email = 'tucker@omnivector.solutions',
                created_at = '2023-08-18T13:55:37.172285',
                updated_at = '2023-08-18T13:55:37.172285',
                is_archived = False,
                description = 'Submission for the Foo job on sample 99 using the bar variant',
                job_script_id = 71,
                slurm_job_id = 1883,
                client_id = 'mega-cluster-1',
                status = CREATED,
                slurm_job_state = PENDING,
                job_script = openapi_client.models.job_script_list_view.JobScriptListView(
                    id = 101, 
                    name = 'test-job-script-88', 
                    owner_email = 'tucker@omnivector.solutions', 
                    created_at = '2023-08-18T13:55:37.172285', 
                    updated_at = '2023-08-18T13:55:37.172285', 
                    is_archived = False, 
                    description = 'This job_scripts runs an Foo job using the bar variant', 
                    parent_template_id = 71, 
                    template = openapi_client.models.job_template_list_view.JobTemplateListView(
                        id = 101, 
                        name = 'test-job-script-88', 
                        owner_email = 'tucker@omnivector.solutions', 
                        created_at = '2023-08-18T13:55:37.172285', 
                        updated_at = '2023-08-18T13:55:37.172285', 
                        is_archived = False, 
                        description = 'This job_scripts runs an Foo job using the bar variant', 
                        identifier = 'App88', 
                        cloned_from_id = 101, ), 
                    cloned_from_id = 101, )
            )
        else:
            return JobSubmissionListView(
                id = 101,
                name = 'test-job-submission-77',
                owner_email = 'tucker@omnivector.solutions',
                created_at = '2023-08-18T13:55:37.172285',
                updated_at = '2023-08-18T13:55:37.172285',
                is_archived = False,
                client_id = 'mega-cluster-1',
                status = CREATED,
        )
        """

    def testJobSubmissionListView(self):
        """Test JobSubmissionListView"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
