# coding: utf-8

"""
    Jobbergate-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.3.0a1
    Contact: info@omnivector.solutions
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.slurm_job_state import SlurmJobState  # noqa: E501

class TestSlurmJobState(unittest.TestCase):
    """SlurmJobState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSlurmJobState(self):
        """Test SlurmJobState"""
        # inst = SlurmJobState()

if __name__ == '__main__':
    unittest.main()
