# coding: utf-8

"""
    Jobbergate-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.3.0a1
    Contact: info@omnivector.solutions
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.job_submissions_api import JobSubmissionsApi  # noqa: E501


class TestJobSubmissionsApi(unittest.TestCase):
    """JobSubmissionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = JobSubmissionsApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_job_submission_agent_update_job_submissions_agent_id_put(self) -> None:
        """Test case for job_submission_agent_update_job_submissions_agent_id_put

        Job Submission Agent Update  # noqa: E501
        """
        pass

    def test_job_submission_create_job_submissions_post(self) -> None:
        """Test case for job_submission_create_job_submissions_post

        Job Submission Create  # noqa: E501
        """
        pass

    def test_job_submission_delete_job_submissions_id_delete(self) -> None:
        """Test case for job_submission_delete_job_submissions_id_delete

        Job Submission Delete  # noqa: E501
        """
        pass

    def test_job_submission_get_job_submissions_id_get(self) -> None:
        """Test case for job_submission_get_job_submissions_id_get

        Job Submission Get  # noqa: E501
        """
        pass

    def test_job_submission_get_list_job_submissions_get(self) -> None:
        """Test case for job_submission_get_list_job_submissions_get

        Job Submission Get List  # noqa: E501
        """
        pass

    def test_job_submission_update_job_submissions_id_put(self) -> None:
        """Test case for job_submission_update_job_submissions_id_put

        Job Submission Update  # noqa: E501
        """
        pass

    def test_job_submissions_agent_active_job_submissions_agent_active_get(self) -> None:
        """Test case for job_submissions_agent_active_job_submissions_agent_active_get

        Job Submissions Agent Active  # noqa: E501
        """
        pass

    def test_job_submissions_agent_pending_job_submissions_agent_pending_get(self) -> None:
        """Test case for job_submissions_agent_pending_job_submissions_agent_pending_get

        Job Submissions Agent Pending  # noqa: E501
        """
        pass

    def test_job_submissions_agent_rejected_job_submissions_agent_rejected_post(self) -> None:
        """Test case for job_submissions_agent_rejected_job_submissions_agent_rejected_post

        Job Submissions Agent Rejected  # noqa: E501
        """
        pass

    def test_job_submissions_agent_submitted_job_submissions_agent_submitted_post(self) -> None:
        """Test case for job_submissions_agent_submitted_job_submissions_agent_submitted_post

        Job Submissions Agent Submitted  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
