# coding: utf-8

"""
    Jobbergate-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.3.0a1
    Contact: info@omnivector.solutions
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.job_submission_detailed_view import JobSubmissionDetailedView  # noqa: E501

class TestJobSubmissionDetailedView(unittest.TestCase):
    """JobSubmissionDetailedView unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> JobSubmissionDetailedView:
        """Test JobSubmissionDetailedView
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `JobSubmissionDetailedView`
        """
        model = JobSubmissionDetailedView()  # noqa: E501
        if include_optional:
            return JobSubmissionDetailedView(
                id = 101,
                name = 'test-job-submission-77',
                owner_email = 'tucker@omnivector.solutions',
                created_at = '2023-08-18T13:55:37.172285',
                updated_at = '2023-08-18T13:55:37.172285',
                is_archived = False,
                description = 'Submission for the Foo job on sample 99 using the bar variant',
                job_script_id = 71,
                slurm_job_id = 1883,
                client_id = 'mega-cluster-1',
                status = CREATED,
                slurm_job_state = PENDING,
                job_script = openapi_client.models.job_script_list_view.JobScriptListView(
                    id = 101, 
                    name = 'test-job-script-88', 
                    owner_email = 'tucker@omnivector.solutions', 
                    created_at = '2023-08-18T13:55:37.172285', 
                    updated_at = '2023-08-18T13:55:37.172285', 
                    is_archived = False, 
                    description = 'This job_scripts runs an Foo job using the bar variant', 
                    parent_template_id = 71, 
                    template = openapi_client.models.job_template_list_view.JobTemplateListView(
                        id = 101, 
                        name = 'test-job-script-88', 
                        owner_email = 'tucker@omnivector.solutions', 
                        created_at = '2023-08-18T13:55:37.172285', 
                        updated_at = '2023-08-18T13:55:37.172285', 
                        is_archived = False, 
                        description = 'This job_scripts runs an Foo job using the bar variant', 
                        identifier = 'App88', 
                        cloned_from_id = 101, ), 
                    cloned_from_id = 101, ),
                execution_directory = '/home/someuser/job-data/test-77',
                report_message = 'Unrecognized SBATCH arguments',
                execution_parameters = {name=job-submission-name, comment=I am a comment},
                slurm_job_info = '
            JobId=2 JobName=apptainer-test
            UserId=ubuntu(1000) GroupId=ubuntu(1000) MCS_label=N/A
            Priority=4294901758 Nice=0 Account=(null) QOS=normal
            JobState=RUNNING Reason=None Dependency=(null)
            Requeue=1 Restarts=0 BatchFlag=1 Reboot=0 ExitCode=0:0
            RunTime=00:01:57 TimeLimit=UNLIMITED TimeMin=N/A
            SubmitTime=2024-01-29T17:42:15 EligibleTime=2024-01-29T17:42:15
            AccrueTime=2024-01-29T17:42:15
            StartTime=2024-01-29T17:42:15 EndTime=Unknown Deadline=N/A
            SuspendTime=None SecsPreSuspend=0 LastSchedEval=2024-01-29T17:42:15 Scheduler=Main
            Partition=compute AllocNode:Sid=10.122.188.182:1278
            ReqNodeList=(null) ExcNodeList=(null)
            NodeList=democluster
            BatchHost=democluster
            NumNodes=1 NumCPUs=6 NumTasks=6 CPUs/Task=1 ReqB:S:C:T=0:0:*:*
            ReqTRES=cpu=6,mem=3903M,node=1,billing=6
            AllocTRES=cpu=6,node=1,billing=6
            Socks/Node=* NtasksPerN:B:S:C=0:0:*:* CoreSpec=*
            MinCPUsNode=1 MinMemoryNode=0 MinTmpDiskNode=0
            Features=(null) DelayBoot=00:00:00
            OverSubscribe=OK Contiguous=0 Licenses=(null) Network=(null)
            Command=(null)
            WorkDir=/tmp
            StdErr=/home/ubuntu/democluster/job.%J.err
            StdIn=/dev/null
            StdOut=/home/ubuntu/democluster/job.%J.out
            Power=
        '
            )
        else:
            return JobSubmissionDetailedView(
                id = 101,
                name = 'test-job-submission-77',
                owner_email = 'tucker@omnivector.solutions',
                created_at = '2023-08-18T13:55:37.172285',
                updated_at = '2023-08-18T13:55:37.172285',
                is_archived = False,
                client_id = 'mega-cluster-1',
                status = CREATED,
        )
        """

    def testJobSubmissionDetailedView(self):
        """Test JobSubmissionDetailedView"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
