# coding: utf-8

"""
    Jobbergate-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.3.0a1
    Contact: info@omnivector.solutions
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.job_template_clone_request import JobTemplateCloneRequest  # noqa: E501

class TestJobTemplateCloneRequest(unittest.TestCase):
    """JobTemplateCloneRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> JobTemplateCloneRequest:
        """Test JobTemplateCloneRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `JobTemplateCloneRequest`
        """
        model = JobTemplateCloneRequest()  # noqa: E501
        if include_optional:
            return JobTemplateCloneRequest(
                name = 'test-job-script-88',
                identifier = 'App88',
                description = 'This job_scripts runs an Foo job using the bar variant',
                template_vars = {param1=7, param2=13}
            )
        else:
            return JobTemplateCloneRequest(
        )
        """

    def testJobTemplateCloneRequest(self):
        """Test JobTemplateCloneRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
