# coding: utf-8

"""
    Jobbergate-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.3.0a1
    Contact: info@omnivector.solutions
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.job_script_templates_api import JobScriptTemplatesApi  # noqa: E501


class TestJobScriptTemplatesApi(unittest.TestCase):
    """JobScriptTemplatesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = JobScriptTemplatesApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_job_script_template_clone_job_script_templates_clone_id_or_identifier_post(self) -> None:
        """Test case for job_script_template_clone_job_script_templates_clone_id_or_identifier_post

        Job Script Template Clone  # noqa: E501
        """
        pass

    def test_job_script_template_create_job_script_templates_post(self) -> None:
        """Test case for job_script_template_create_job_script_templates_post

        Job Script Template Create  # noqa: E501
        """
        pass

    def test_job_script_template_delete_file_job_script_templates_id_or_identifier_upload_template_file_name_delete(self) -> None:
        """Test case for job_script_template_delete_file_job_script_templates_id_or_identifier_upload_template_file_name_delete

        Job Script Template Delete File  # noqa: E501
        """
        pass

    def test_job_script_template_delete_job_script_templates_id_or_identifier_delete(self) -> None:
        """Test case for job_script_template_delete_job_script_templates_id_or_identifier_delete

        Job Script Template Delete  # noqa: E501
        """
        pass

    def test_job_script_template_garbage_collector_job_script_templates_upload_garbage_collector_delete(self) -> None:
        """Test case for job_script_template_garbage_collector_job_script_templates_upload_garbage_collector_delete

        Job Script Template Garbage Collector  # noqa: E501
        """
        pass

    def test_job_script_template_get_file_job_script_templates_id_or_identifier_upload_template_file_name_get(self) -> None:
        """Test case for job_script_template_get_file_job_script_templates_id_or_identifier_upload_template_file_name_get

        Job Script Template Get File  # noqa: E501
        """
        pass

    def test_job_script_template_get_job_script_templates_id_or_identifier_get(self) -> None:
        """Test case for job_script_template_get_job_script_templates_id_or_identifier_get

        Job Script Template Get  # noqa: E501
        """
        pass

    def test_job_script_template_get_list_job_script_templates_get(self) -> None:
        """Test case for job_script_template_get_list_job_script_templates_get

        Job Script Template Get List  # noqa: E501
        """
        pass

    def test_job_script_template_update_job_script_templates_id_or_identifier_put(self) -> None:
        """Test case for job_script_template_update_job_script_templates_id_or_identifier_put

        Job Script Template Update  # noqa: E501
        """
        pass

    def test_job_script_template_upload_file_job_script_templates_id_or_identifier_upload_template_file_type_put(self) -> None:
        """Test case for job_script_template_upload_file_job_script_templates_id_or_identifier_upload_template_file_type_put

        Job Script Template Upload File  # noqa: E501
        """
        pass

    def test_job_script_workflow_delete_file_job_script_templates_id_or_identifier_upload_workflow_delete(self) -> None:
        """Test case for job_script_workflow_delete_file_job_script_templates_id_or_identifier_upload_workflow_delete

        Job Script Workflow Delete File  # noqa: E501
        """
        pass

    def test_job_script_workflow_get_file_job_script_templates_id_or_identifier_upload_workflow_get(self) -> None:
        """Test case for job_script_workflow_get_file_job_script_templates_id_or_identifier_upload_workflow_get

        Job Script Workflow Get File  # noqa: E501
        """
        pass

    def test_job_script_workflow_upload_file_job_script_templates_id_or_identifier_upload_workflow_put(self) -> None:
        """Test case for job_script_workflow_upload_file_job_script_templates_id_or_identifier_upload_workflow_put

        Job Script Workflow Upload File  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
