# coding: utf-8

"""
    Jobbergate-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.3.0a1
    Contact: info@omnivector.solutions
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.job_script_create_request import JobScriptCreateRequest  # noqa: E501

class TestJobScriptCreateRequest(unittest.TestCase):
    """JobScriptCreateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> JobScriptCreateRequest:
        """Test JobScriptCreateRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `JobScriptCreateRequest`
        """
        model = JobScriptCreateRequest()  # noqa: E501
        if include_optional:
            return JobScriptCreateRequest(
                name = 'test-job-script-88',
                description = 'This job_scripts runs an Foo job using the bar variant'
            )
        else:
            return JobScriptCreateRequest(
                name = 'test-job-script-88',
        )
        """

    def testJobScriptCreateRequest(self):
        """Test JobScriptCreateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
