"""Added status column

Revision ID: 75325d649ee2
Revises: 5f987ab31acf
Create Date: 2022-03-19 13:40:18.795434

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "75325d649ee2"
down_revision = "5f987ab31acf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("job_submissions", sa.Column("client_id", sa.String()))
    op.execute("update job_submissions set client_id='UNKNOWN'")
    op.create_index(
        op.f("ix_job_submissions_client_id"), "job_submissions", ["client_id"], unique=False
    )
    op.alter_column("job_submissions", "client_id", nullable=False)

    status = postgresql.ENUM(
        "CREATED",
        "SUBMITTED",
        "COMPLETED",
        "FAILED",
        "UNKNOWN",
        name="jobsubmissionstatus",
    )
    status.create(op.get_bind())
    op.add_column(
        "job_submissions",
        sa.Column("status", status),
    )
    op.execute("update job_submissions set status='UNKNOWN'")
    op.create_index(op.f("ix_job_submissions_status"), "job_submissions", ["status"], unique=False)
    op.alter_column("job_submissions", "status", nullable=False)
    # TODO set columns to COMPLETED by default
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_job_submissions_status"), table_name="job_submissions")
    op.drop_index(op.f("ix_job_submissions_client_id"), table_name="job_submissions")
    op.drop_column("job_submissions", "status")
    op.drop_column("job_submissions", "client_id")
    # ### end Alembic commands ###
