"""Add "execution parameters" to Job Submissions

Revision ID: 81bf4eecc575
Revises: d22da0741b7f
Create Date: 2022-10-19 17:40:15.929532

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "81bf4eecc575"
down_revision = "d22da0741b7f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "job_submissions",
        sa.Column("execution_parameters", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("job_submissions", "execution_parameters")
    # ### end Alembic commands ###
