"""Moved job scripts to S3, removing string column

Revision ID: 023f534b159d
Revises: edfdea225579
Create Date: 2022-05-25 17:13:27.014460

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "023f534b159d"
down_revision = "edfdea225579"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("job_scripts", "job_script_data_as_string")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "job_scripts",
        sa.Column("job_script_data_as_string", sa.String(), nullable=False),
    )
    # ### end Alembic commands ###
