"""Continue to refactor Jobbergate Application File Management

Revision ID: 0fba232ba7d1
Revises: d22da0741b7f
Create Date: 2022-08-26 17:41:14.340400

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "0fba232ba7d1"
down_revision = "d22da0741b7f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("applications", "application_config")
    # Set updated status to false everywhere, because application_file was dropped
    op.execute("UPDATE applications SET application_uploaded=false")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "applications",
        sa.Column(
            "application_config",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
    )
    # Set updated status to false everywhere
    op.execute("UPDATE applications SET application_uploaded=false")
    # ### end Alembic commands ###
