"""PFT-1080 Make foreign keys nullable

Revision ID: e6e9e1f58ecc
Revises: 81bf4eecc575
Create Date: 2023-03-27 10:56:20.282344

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "e6e9e1f58ecc"
down_revision = "81bf4eecc575"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("job_scripts", "application_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("job_submissions", "job_script_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("job_submissions", "job_script_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("job_scripts", "application_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
