FROM python:3.14-slim-bookworm

RUN apt update && apt --no-install-recommends install -y build-essential git gcc libpq-dev

COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv

COPY . /app

WORKDIR /app

# Install only jobbergate-api and its dependencies (including dev)
RUN uv sync --package jobbergate-api

ENTRYPOINT /app/jobbergate-api/dev_tools/entrypoint.sh
#CMD ["uvicorn", "jobbergate_api.main:app", "--host", "0.0.0.0", "--port", "80"]
