FROM tiangolo/uvicorn-gunicorn-fastapi:python3.8-slim

RUN apt-get -y update
RUN apt-get install -y --fix-missing build-essential cmake libpq-dev curl

RUN pip install 'poetry==1.1.7'

ENV MODULE_NAME="jobbergate_api.main"

COPY ./pyproject.toml /app/
COPY ./poetry.lock /app/
COPY ./dev_tools/entrypoint.sh /app/
RUN chmod +x /app/entrypoint.sh

ARG AWS_ACCESS_KEY_ID
ENV AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID

ARG AWS_SECRET_ACCESS_KEY
ENV AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY

RUN poetry config virtualenvs.create false --local
RUN poetry install

VOLUME /app/jobbergate_api
VOLUME /app/dev_tools
VOLUME /app/alembic
