name: jobbergate-agent
base: core24
version: '0.0.0'
summary: The Jobbergate Agent snap
adopt-info: jobbergate-agent
license: MIT
description: |
  The Jobbergate Agent Snap deploys the Jobbergate Agent Python package on your host system. This agent
  is an essencial component of the Jobbergate platform for managing and submitting jobs to HPC clusters.

  This snap requires a few configuration values to be set before it can be used. These values are:
  - base-api-url: The URL of the Jobbergate API server where the agent will send its data. Setting/unsetting this value is more interesting when using the snap in a development environment; do not change it otherwise.

  - oidc-domain: The domain of the OIDC server that the agent will use for authentication. Setting/unsetting this value is more interesting when using the snap in a development environment; do not change it otherwise.

  - oidc-client-id: The client ID of the OIDC application that the agent will use for authentication.

  - oidc-client-secret: The client secret of the OIDC application that the agent will use for authentication.

  - task-jobs-interval-seconds: The interval in seconds at which the agent will run its internal task jobs, hence sending data to the Jobbergate API server. This is optional and defaults to 30 seconds.

  - sbatch-path: The absolute path to the *sbatch* command on the host system. This is optional and defaults to /usr/bin/sbatch.

  - scontrol-path: The absolute path to the *scontrol* command on the host system. This is optional and defaults to /usr/bin/scontrol.

  - default-slurm-work-dir: The default working directory that the agent will use when submitting jobs to the SLURM cluster. This is optional and defaults to /tmp.

  - slurm-user-mapper: The user mapper that the agent will use to map the system user name to the SLURM user name. This is optional and defaults to none.

  - single-user-submitter: The system user name that the agent will use to submit jobs to the SLURM cluster on behalf of in case the *single-user-submitter* is not set. This is optional and defaults to *ubuntu*.

  - write-submission-files: A boolean value (true, false) that indicates whether the agent should write submission files to disk. This is optional and defaults to false.

  - influx-dsn: The DSN of the InfluxDB server that the agent will use to fetch job metrics data. It only allows the following schemes: 'influxdb', 'https+influxdb' and 'udp+influxdb'. This is optional and defaults to none.

  - influx-pool-size: The size of the InfluxDB connection pool that the agent will use to fetch job metrics data. This is optional and defaults to 10.

  - influx-ssl: A boolean value (true, false) that indicates whether the agent should use SSL to connect to the InfluxDB server. If true, `influx-cert-path` must be provided. This is optional and defaults to false.

  - influx-verify-ssl: A boolean value (true, false) that indicates whether the agent should verify the SSL certificate of the InfluxDB server. This is optional and defaults to false.

  - influx-timeout: The timeout in seconds that the agent will use when connecting to the InfluxDB server. This is optional and defaults to none.

  - influx-udp-port: The UDP port that the agent will use to connect to the InfluxDB server. This is optional and defaults to 4444.

  - influx-cert-path: The absolute path to the SSL certificate that the agent will use to connect to the InfluxDB server. This is optional and defaults to none.

  For learning more about Jobbergate and how it can be used on Vantage, please visit https://docs.vantagehpc.io

grade: stable
confinement: classic

parts:
  jobbergate-agent:
    source: .
    plugin: python
    python-packages:
    - jobbergate-agent==5.5.0
    build-packages:
    - python3
    - gcc
    - g++
    - dpkg-dev
    stage-packages:
    - python3.12-minimal
    - python3.12-venv
    - libpython3.12-minimal
    - libpython3.12-stdlib
    build-attributes:
    - enable-patchelf
    override-stage: |
     craftctl default
     craftctl set version="$($SNAPCRAFT_PART_INSTALL/bin/python3 -m pip show jobbergate-agent | grep Version | awk '{print $2}')"

  hooks:
    plugin: dump
    source: hooks
    organize:
      bin/: snap/hooks/

  wrappers:
    plugin: dump
    source: wrappers/
    source-type: local

apps:
  daemon:
    command: bin/jg-run
    daemon: simple
    install-mode: disable
    environment:
      PYTHONPATH: "$SNAP/lib/python3.12/site-packages"
      PYTHONHOME: "$SNAP/usr"
      PATH: "$SNAP/bin:$PATH"

  start:
    command: commands/daemon.start
    daemon: simple
    install-mode: disable
    environment:
      PATH: "$SNAP/bin:$PATH"

  stop:
    command: commands/daemon.stop
    daemon: simple
    install-mode: disable
    environment:
      PATH: "$SNAP/bin:$PATH"

  restart:
    command: commands/daemon.restart
    daemon: simple
    install-mode: disable
    environment:
      PATH: "$SNAP/bin:$PATH"
