apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  finalizers:
    - kubernetes.io/pvc-protection
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    app: minio
spec:
  accessModes:
    - ReadWriteOnce
  {{- with .Values.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.minio.storageSize }}
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: jobbergate-minio-access-key
  labels:
    k8s-app: jobbergate
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  length: 20
  digits: 5
  symbols: 2
  symbolCharacters: "-_"
  noUpper: false
  allowRepeat: true
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: jobbergate-minio-secret-key
  labels:
    k8s-app: jobbergate
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  length: 30
  digits: 18
  symbols: 5
  symbolCharacters: "-_$#{}[]"
  noUpper: false
  allowRepeat: true
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jobbergate-minio-credentials
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    k8s-app: jobbergate
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: {{ .Values.externalSecrets.clusterSecretStoreName }}
    kind: ClusterSecretStore
  target:
    name: jobbergate-minio-credentials
    immutable: true
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: "jobbergate-minio-access-key"
      rewrite:
        - regexp:
            source: "(.*)"
            target: "MINIO_ACCESS_KEY"
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: "jobbergate-minio-secret-key"
      rewrite:
        - regexp:
            source: "(.*)"
            target: "MINIO_SECRET_KEY"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobbergate-minio
  labels:
    app: minio
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  selector:
    matchLabels:
      app: jobbergate-minio
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jobbergate-minio
    spec:
      automountServiceAccountToken: false
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: minio-pvc
      containers:
        - name: minio
          image: "{{ .Values.minio.image.repository }}:{{ .Values.minio.image.tag }}"
          args:
            - server
            - /storage
          envFrom:
            - secretRef:
                name: jobbergate-minio-credentials
                optional: false
          ports:
            - containerPort: 9000
              hostPort: 9000
          volumeMounts:
            - name: storage
              mountPath: /storage
          resources:
            {{- toYaml .Values.minio.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: jobbergate-minio
  labels:
    app: minio
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    app: jobbergate-minio
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: check-jobbergate-minio-status
  annotations:
    argocd.argoproj.io/sync-wave: "0"
data:
  check-minio-status.sh: |
    while [[ $(curl -s -o /dev/null -w "%{http_code}" http://jobbergate-minio.$NAMESPACE.svc.cluster.local:9000) != "403" ]]
      do
        echo "MinIO deployment isn't ready yet."
        sleep 5
    done

    echo "MinIO deployment is ready. Exitting with code 0."

    exit 0
