{{- if and (eq .Values.storage.backend "s3") (not .Values.storage.s3.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: jobbergate-s3-credentials
  labels:
    k8s-app: jobbergate
type: Opaque
stringData:
  {{ .Values.storage.s3.existingSecretAccessKeyIdKey }}: {{ .Values.storage.s3.accessKeyId | quote }}
  {{ .Values.storage.s3.existingSecretSecretAccessKeyKey }}: {{ .Values.storage.s3.secretAccessKey | quote }}
{{- end }}
