apiVersion: v1
kind: Service
metadata:
  name: jobbergate-api
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: jobbergate-api
