FROM slurm-docker-cluster

WORKDIR /app

RUN apt update && apt install -y curl libpq-dev gcc python3-dev python3-pip && \
    ln -s /usr/bin/python3 /usr/bin/python

RUN curl -sSL  https://install.python-poetry.org | \
    POETRY_HOME=/opt/poetry POETRY_VERSION=1.5.1 python && \
    ln -s /opt/poetry/bin/poetry /usr/local/bin/poetry && \
    poetry config virtualenvs.create false

COPY ./pyproject.toml ./poetry.lock* ./README* ./LICENSE* /app/
COPY ./etc/entrypoint.sh /app/entrypoint.sh
WORKDIR /app

VOLUME /app/jobbergate_agent
VOLUME /jobbergate-core

ENTRYPOINT /app/entrypoint.sh
