FROM python:3.12-slim-bookworm

WORKDIR /app

RUN apt update && apt install -y curl libpq-dev gcc

RUN curl -sSL  https://install.python-poetry.org | \
    POETRY_HOME=/opt/poetry POETRY_VERSION=1.5.1 python && \
    cd /usr/local/bin && \
    ln -s /opt/poetry/bin/poetry && \
    poetry config virtualenvs.create false

COPY ./pyproject.toml ./poetry.lock* ./README* ./LICENSE* /app/
COPY ./etc/entrypoint.sh /app/entrypoint.sh
WORKDIR /app

VOLUME /app/jobbergate_agent
VOLUME /jobbergate-core

ENTRYPOINT /app/entrypoint.sh
