# General
shared_preload_libraries = 'timescaledb'

# Background workers
max_worker_processes=10000
timescaledb.max_background_workers=10000

# Replication configs
listen_addresses = '*'
max_wal_senders = 10
max_connections = 1000
shared_buffers = 256MB

# Logging
# log_destination = 'stderr'
# logging_collector = on
# log_directory = 'pg_log'
# log_filename= 'postgresql-%Y-%m-%d_%H%M%S.log'
# log_min_messages = DEBUG2
# log_error_verbosity = verbose