name: Build Documentation

on:
  push:
    paths:
      - "jobbergate-docs/docs/**"
      - "jobbergate-api/jobbergate_api/**"
      - "jobbergate-cli/jobbergate_cli/**"
      - "jobbergate-core/jobbergate_core/**"
      - "jobbergate-agent/jobbergate_agent/**"
      - ".github/workflows/build_docs.yaml"
    branches:
      - "main"

permissions:
  contents: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: 3.14

      - name: Install uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0

      - name: Build Documentation
        working-directory: jobbergate-docs
        run: make docs

      - name: Deploy documentation
        uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4.1.0
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: jobbergate-docs/docs/site
