name: Build Documentation

on:
  push:
    paths:
      - "jobbergate-docs/docs/**"
      - "jobbergate-api/jobbergate_api/**"
      - "jobbergate-cli/jobbergate_cli/**"
      - "jobbergate-core/jobbergate_core/**"
      - "jobbergate-agent/jobbergate_agent/**"
      - ".github/workflows/build_docs.yaml"
    branches:
      - "main"

permissions:
  contents: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: 3.14

      - name: Install uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0

      - name: Build Documentation
        working-directory: jobbergate-docs
        run: make docs

      - name: Deploy documentation
        uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4.1.0
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: jobbergate-docs/docs/site
