name: "Test"

on:
  push:
    branches:
      - main
      - release/**
  pull_request:

jobs:
  component-tests:
    name: "jobbergate tests"
    runs-on: "ubuntu-24.04"
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
        component: [core, cli, agent]
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ matrix.python-version }}
          architecture: "x64"
      - uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
      - name: "run quality control checks"
        working-directory: jobbergate-${{ matrix.component }}
        run: make qa

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          working-directory: jobbergate-${{ matrix.component }}
          flags: ${{ matrix.component }}
          env_vars: OS,PYTHON
          token: ${{ secrets.CODECOV_TOKEN }}
          files: tests/coverage.xml
          disable_search: true
          fail_ci_if_error: true

  api-tests:
    name: "jobbergate-api tests"
    runs-on: "ubuntu-24.04"
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Run QA
        working-directory: jobbergate-composed
        run: |
          docker compose --profile dev build jobbergate-api-qa
          docker compose --profile dev run --rm jobbergate-api-qa

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          working-directory: jobbergate-api
          flags: api
          env_vars: OS,PYTHON
          token: ${{ secrets.CODECOV_TOKEN }}
          files: tests/coverage.xml
          disable_search: true
          fail_ci_if_error: true

  agent-snap-tests:
    name: "jobbergate-agent-snap tests"
    runs-on: "ubuntu-22.04"
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.12.3"
          architecture: "x64"
      - name: "run quality control checks"
        working-directory: jobbergate-agent-snap
        run: |
          python -m pip install tox==4.20.0
          make qa
