name: "Test"

on:
  push:
    branches:
      - main
      - release/**
  pull_request:

jobs:
  component-tests:
    name: "jobbergate tests"
    runs-on: "ubuntu-24.04"
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
        component: [core, cli, agent]
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: ${{ matrix.python-version }}
          architecture: "x64"
      - uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2
      - name: "run quality control checks"
        working-directory: jobbergate-${{ matrix.component }}
        run: make qa

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          working-directory: jobbergate-${{ matrix.component }}
          flags: ${{ matrix.component }}
          env_vars: OS,PYTHON
          token: ${{ secrets.CODECOV_TOKEN }}
          files: tests/coverage.xml
          disable_search: true
          fail_ci_if_error: true

  api-tests:
    name: "jobbergate-api tests"
    runs-on: "ubuntu-24.04"
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Run QA
        working-directory: jobbergate-composed
        run: |
          docker compose --profile dev build jobbergate-api-qa
          docker compose --profile dev run --rm jobbergate-api-qa

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          working-directory: jobbergate-api
          flags: api
          env_vars: OS,PYTHON
          token: ${{ secrets.CODECOV_TOKEN }}
          files: tests/coverage.xml
          disable_search: true
          fail_ci_if_error: true

  agent-snap-tests:
    name: "jobbergate-agent-snap tests"
    runs-on: "ubuntu-22.04"
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: "3.12.3"
          architecture: "x64"
      - name: "run quality control checks"
        working-directory: jobbergate-agent-snap
        run: |
          python -m pip install tox==4.20.0
          make qa
